<<<<<<< HEAD
import "./globals.css";
//стили и грифиы
export const metadata = {
  title: "Soller",
  description: "Solar products in your home",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 519c352 (Initial commit from Create Next App)
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
=======
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
>>>>>>> 519c352 (Initial commit from Create Next App)
        {children}
      </body>
    </html>
  );
}
